version: '3.2'
services:
  gdc-web:
    image: gdc-website:production
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gdc_website_container
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VIRTUAL_HOST=gdc.mec.ac.in
